<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>eu.europa.ec.joinup.sd-dss</groupId>
        <artifactId>sd-dss</artifactId>
        <version>6.6-SNAPSHOT</version>
    </parent>

    <artifactId>dss-lote-validation-xml</artifactId>
    <name>DSS LoTE Validation of XML format</name>
    <description>TS 119 602 XML LoTE (List of Trusted Entities) loading, parsing and validation business</description>

    <properties>
        <module-name>jpms_dss_lote_validation_xml</module-name>
    </properties>

    <dependencies>
        <dependency>
            <groupId>eu.europa.ec.joinup.sd-dss</groupId>
            <artifactId>specs-lote-xml</artifactId>
        </dependency>
        <dependency>
            <groupId>eu.europa.ec.joinup.sd-dss</groupId>
            <artifactId>dss-lote-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>eu.europa.ec.joinup.sd-dss</groupId>
            <artifactId>dss-xades</artifactId>
        </dependency>

        <dependency>
            <groupId>eu.europa.ec.joinup.sd-dss</groupId>
            <artifactId>dss-validation</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>eu.europa.ec.joinup.sd-dss</groupId>
            <artifactId>dss-test</artifactId>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>